---

galaxy_info:
  author: Sergei Maertens
  description: Install and configure postfix-policyd-spf-python
  company: Regex IT

  issue_tracker_url: https://github.com/sergei-maertens/ansible-collection-mailservers/issues

  license: MIT

  min_ansible_version: '2.12'

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  # Optionally specify the branch Galaxy will use when accessing the GitHub
  # repo for this role. During role install, if no tags are available,
  # Galaxy will use this branch. During import Galaxy will access files on
  # this branch. If Travis integration is configured, only notifications for this
  # branch will be accepted. Otherwise, in all cases, the repo's default branch
  # (usually master) will be used.
  github_branch: main

  platforms:
    # Debian and derivatives
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - jammy

  galaxy_tags: []

dependencies: []
