---

- name: Install packages
  ansible.builtin.package:
    state: present
    name:
      - spamassassin
      - spamc
      - spamass-milter

- name: Template out configuration
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: spamass-milter.j2
      dest: /etc/default/spamass-milter
    - src: spamassassin.j2
      dest: /etc/default/spamassassin
    - src: local.cf.j2
      dest: /etc/spamassassin/local.cf
  notify:
    - restart spamassassin

- name: Ensure daemon is running and enabled
  ansible.builtin.service:
    name: spamassassin
    state: started
    enabled: true
