---

# Variables used in default main.cf

## TLS
postfix_ssl_cert_file: /etc/ssl/certs/ssl-cert-snakeoil.pem
postfix_ssl_key_file: /etc/ssl/private/ssl-cert-snakeoil.key

## Networking
postfix_myhostname: "{{ ansible_hostname }}"  # should be machine/system name
postfix_extra_local_networks:
  - 172.16.0.0/12  # docker
postfix_inet_interfaces:
  - all
postfix_inet_protocols:
  - all

# Custom configuration

## Dovecot
postfix_dovecot_enabled: no

## Virtual mailboxes via PostgreSQL table
postfix_vmail_postgres: no

postfix_db_user: postfix
postfix_db_password: postfix
postfix_db_name: postfix
# See http://www.postfix.org/pgsql_table.5.html
postfix_db_hosts: localhost:5432

postfix_vmail_basedir: /var/mail/domains
postfix_vmail_uid: 1005
postfix_vmail_gid: "{{ postfix_vmail_uid }}"
