---

# Deploy the postfixer app with docker


- name: Ensure a separate network exists
  docker_network:
    name: "postfixer"

- name: Create a volume for the logs
  docker_volume:
    name: postfixer-logs

- name: Ensure web container runs
  docker_container:
    name: postfixer-web
    image: "{{ postfixer_image }}"
    pull: yes
    hostname: postfixer-django
    state: started
    restart: no
    restart_policy: always
    networks:
      - name: "postfixer"
    volumes:
      # mount postgresql socket
      - "/var/run/postgresql:/var/run/postgresql"
      # logs
      - "postfixer-logs:/app/log"
    env:
      SECRET_KEY: "{{ postfixer_secret_key | mandatory }}"
      ALLOWED_HOSTS: "localhost,{{ postfixer_hostname }}"
      DB_HOST: "{{ postfixer_db_host }}"
      DB_PORT: "{{ postfixer_db_port | string }}"
      DB_NAME: "{{ postfixer_db_name }}"
      DB_USER: "{{ postfixer_db_user }}"
      DB_PASSWORD: "{{ postfixer_db_password }}"

    published_ports:
      - "127.0.0.1:{{ postfixer_port }}:8000"
