---

# Creates the database for the application

- name: Ensure postgres + deps are installed
  apt:
    name:
    - postgresql
    - python3-psycopg2

- name: Create application database user
  postgresql_user:
    name: "{{ postfixer_db_user }}"
    password: "{{ postfixer_db_password }}"
    role_attr_flags: NOCREATEDB,NOSUPERUSER,NOCREATEROLE
  become: yes
  become_user: postgres

- name: Create application database
  postgresql_db:
    name: "{{ postfixer_db_name }}"
    encoding: 'UTF-8'
    owner: "{{ postfixer_db_user }}"
  become: yes
  become_user: postgres

- name: Allow local (unix socket) password access
  lineinfile:
    dest: "/etc/postgresql/{{ postfixer_postgresql_version }}/main/pg_hba.conf"
    line: "local   {{ postfixer_db_name }}    {{ postfixer_db_user }}    md5"
    insertbefore: "^# \"local\" is for Unix domain socket connections only"
  notify:
    - reload postgres

- name: Allow IPv4 (tcp) password access
  lineinfile:
    dest: "/etc/postgresql/{{ postfixer_postgresql_version }}/main/pg_hba.conf"
    line: "host    {{ postfixer_db_name }}    {{ postfixer_db_user }}  127.0.0.1/32  md5"
    insertbefore: "^# IPv6 local connections"
  notify:
    - reload postgres
